require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - rack_session_redis.gemspec
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 10

RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false

# NOTE: we need to replicate existing functionality of redis-store
Security/MarshalLoad:
  Enabled: false

Style/Documentation:
  Enabled: false
