require: rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile.lock

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - test/**/*
    - rack_session_redis.gemspec
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 10

Naming/VariableNumber:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - test/**/*
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OpenStructUse:
  Exclude:
    - test/**/*
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/SpecialGlobalVars:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/WordArray:
  EnforcedStyle: percent
Style/ZeroLengthPredicate:
  Enabled: false
Layout/LineLength:
  Max: 200
Lint/AmbiguousBlockAssociation:
  Enabled: false

Minitest/AssertRaisesCompoundBody:
  Enabled: false # seems to have an issue in CI, disabling this cop for now
